mysite/blog/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('about/', views.about, name='about'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post

latest_post_list = Post.objects.order_by('-updated_datetime')
sitemaps = {
    'blog': GenericSitemap({
        #'queryset': Post.objects.all(),
        'queryset':latest_post_list,
        'date_field': 'updated_datetime',
    }, priority=0.9),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils.text import slugify
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    #text = models.TextField()
    text = MarkdownxField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    def formatted_markdown(self):
        return markdownify(self.text)

    def get_absolute_url(self):
        return reverse('post:post_detail',
                   args=[str(self.slug)])

# to save slug
def save(self, *args, **kwargs):
    self.slug = slugify(self.title)
    super().save(*args, **kwargs)

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post
# Create your views here.
def about(request):
    return HttpResponse('このブログサイトについて....')

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/detail.html', {'post':post})

def index(request):
    posts = Post.objects.order_by('-created_datetime')
    return render(request, 'blog/index.html',{'posts':posts})

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>
  <!-- Googleアナリティクス -->
  <!-- Bootstrap etc-->
</head>
<body>
{% block content %}
{% endblock %}
<button onclick="topFunction()" id="myBtn" title="Go to top">▲</button>
</body>
</html>

mysite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block title %} {{ post.title }}:僕のブログ {% endblock %}
{% block content %}
<h1 style="text-align: center;" >{{ post.title }}</h1>
<div style="text-align: center;">
{{ post.formatted_markdown|safe }}
<a href="http://127.0.0.1:8080/catalogue/">購入はこちら</a>
</div>
<hr>
<div style="text-align: center;" style="font-size:0.6em">
{{ post.created_datetime }}
<br>
{{ post.updated_datetime }}
</div>
<hr>
<a href="{% url 'post:index'%}">トップページへ戻る</a>
{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %} 食品ロス解決商品 {% endblock %}

{% block content %}
  <h1 class="cp_h1title1" style="text-align: center;">食材循環活動(仮)</h1>

<!--
  <h3 style="text-align: center;">参考 ; https://blog.codecamp.jp/python-blog-django</h3>
--> 
  <div style="width: 70%;margin: 0px auto;">
    <hr />
    {% for post in posts %}
    <div>
      <h3>{{ post.title }}</h3>
      <div>{{ post.text | truncatechars:100 }}</div>
      <div style="text-align: right;">
        <a href="{% url 'post:post_detail' slug=post.slug %}">記事を読む</a>
      </div>
    </div>
    <hr />
    {% endfor %}
  </div>
{% endblock %}